export const FETCH_OFFERS_REQUEST = "FETCH_OFFERS_REQUEST";
export const FETCH_OFFERS_SUCCESS = "FETCH_OFFERS_SUCCESS";
export const FETCH_OFFERS_ERROR = "FETCH_OFFERS_ERROR";

export const FETCH_OFFER_REQUEST = "FETCH_OFFER_REQUEST";
export const FETCH_OFFER_SUCCESS = "FETCH_OFFER_SUCCESS";
export const FETCH_OFFER_ERROR = "FETCH_OFFER_ERROR";

export const AUTH_USER_REQUEST = "AUTH_USER_REQUEST";
export const AUTH_REQUEST_SUCCESS = "AUTH_REQUEST_SUCCESS";
export const AUTH_REQUEST_FAIL = "AUTH_REQUEST_FAIL";
export const DEAUTH_USER = "DEAUTH_USER";
